### ISSUE TITLE
[Help may not issue]Connection is not subscribed and is idle

### ISSUE THREAD

**Issue by efialtisgr** [liampauling/betfairlightweight#11]
Hi, 

Thanks for your library. 

Im facing some issues with streaming only, the rest working just fine ! (great work though)

I tried this

`betfair_socket = trading.streaming.create_stream(unique_id=1)
betfair_socket.start(async=False)
betfair_socket.authenticate()
betfair_socket.subscribe_to_markets(market_filter={'eventTypeIds':['1'],
                                                   'inPlayOnly': True,
                                                   'marketTypes':["MATCH_ODDS"]},
                                    market_data_filter={'fields': ['EX_BEST_OFFERS']})
`

and I'm ending up with this result:

`1 {"op":"connection","connectionId":"006-051016081016-209520"}

None {"op":"status","statusCode":"FAILURE","errorCode":"TIMEOUT","errorMessage":"Connection is not subscribed and is idle: 15000 ms","connectionClosed":true,"connectionId":"006-051016081016-209520"}
`

Any help pls where im messing up ? 

Once more thanks again for your effort.

Regards

**Comment by liampauling** [comment]
Hi,

Glad its working for you, the reason you are being closed is because async needs to be True if you are not creating a separate thread for it in order to handle the socket:

`betfair_socket = trading.streaming.create_stream(unique_id=1)
betfair_socket.start(async=True)
betfair_socket.authenticate()
betfair_socket.subscribe_to_markets(market_filter={'eventTypeIds':['1'], 'inPlayOnly': True, 'marketTypes':["MATCH_ODDS"]}, market_data_filter={'fields': ['EX_BEST_OFFERS']})

while True:
    time.sleep(0.5)
`

The idea being that you can create a separate thread if required to catch any errors, without this the your script blocks at .start due to the while loop that is polling the socket.

Just so you know, I am not using streaming in production and still lacking on test coverage.

**Comment by efialtisgr** [comment]
Thanks ,

Sadly im getting another msg [NOT_AUTHORIZED]

So i suppose my AppKey, needs an upgrade or somthing :) 

Anyway thanks a lot !

Regards

**Comment by liampauling** [comment]
You need to register, send an email to Neil bdp@betfair.com
