### ISSUE TITLE
Calling socket.stop() causes an AttributeError

### ISSUE THREAD

**Issue by oughtotrade** [liampauling/betfairlightweight#60]
When I call stop() on the listener socket I get the following AttributeError.

```
<snip>
  File "/home/anon/.virtualenvs/anon/local/lib/python2.7/site-packages/betfairlightweight/streaming/betfairstream.py", line 56, in stop
    if self._socket is not None and not self._socket._closed:
AttributeError: 'SSLSocket' object has no attribute '_closed'

```

I can't find this `_closed` attribute in any of the Python documentation or else I'd try and file a PR for you!

**Comment by liampauling** [comment]
Thanks,  _closed is a protected member which I assume py2.7 doesn't have, will just remove so that the shutdown is attempted regardless. 

Just reviewed the source code for socket and _socket, it looks as though shutdown actually calls close() so this can be cleaned up as well.

https://github.com/python/cpython/blob/3.6/Lib/socket.py
https://github.com/biosbits/bits/blob/master/python/_socket.py

**Comment by oughtotrade** [comment]
Thanks, good result. I'd patched it locally in the same way you modified it and it was working fine (for py2.7 anyway).
