### ISSUE TITLE
Handicap / Streaming bug

### ISSUE THREAD

**Issue by liampauling** [liampauling/betfairlightweight#72]
It seems that on handicap markets the selectionId will be repeated:

`
[{"marketId":"1.131434037","isMarketDataDelayed":false,"status":"OPEN","betDelay":0,"bspReconciled":false,"complete":true,"inplay":false,"numberOfWinners":0,"numberOfRunners":66,"numberOfActiveRunners":66,"lastMatchTime":"2017-05-13T09:06:13.495Z","totalMatched":350.69,"totalAvailable":15649.09,"crossMatching":true,"runnersVoidable":false,"version":1645619435,"runners":[{"selectionId":579339,"handicap":-4.0,"status":"ACTIVE"},{"selectionId":197960,"handicap":4.0,"status":"ACTIVE"},{"selectionId":579339,"handicap":-3.75,"status":"ACTIVE"},{"selectionId":197960,"handicap":3.75,"status":"ACTIVE"},{"selectionId":579339,"handicap":-3.5,"status":"ACTIVE"},{"selectionId":197960,"handicap":3.5,"status":"ACTIVE"},{"selectionId":579339,"handicap":-3.25,"status":"ACTIVE"},{"selectionId":197960,"handicap":3.25,"status":"ACTIVE"}, ...
`

The streaming cache uses the selectionId as a primary key which isn't going to work on handicap markets.

**Comment by seaders** [comment]
What market is that, is it a dynamic handicap market, I can't find info on it?  I know for US Sports, they have multiple handicap markets, but each of those will have different sets of selections "Atlanta +2.5" will have a different market id,  selection id to "Atlanta +1.5".  In "normal" handicap markets, handicap isn't even filled in, isn't that right?  (this is again why I'm asking about which market this is)

You could tuple the key up, have it as (selectionId, handicap)?  When I'm processing multiple markets, that's what I normally end up doing.  Leave it as a tuple, or a str "{selectionId}::{extra}" so that I have both pieces of data for a handicap, and over/under market, but it's just "WIN" for moneyline.

**Comment by liampauling** [comment]
Not sure on the market, was just testing something; subscribed to all markets and looked for anomalies and this popped up. Yeh a tuple lookup will work but its annoying for just a handful of markets.
